version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - test-net
    restart: on-failure
  client:
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - test-net
    restart: on-failure
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=5001
      - CLIENT_PORT=3000

networks:
  test-net:
    driver: bridge
